// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4Dm-tKwExpd71hetpa210CIW5m3DxzQY',
    appId: '1:468632398862:ios:388f9bbe73f5d7842f605f',
    messagingSenderId: '468632398862',
    projectId: 'chessever-53078',
    storageBucket: 'chessever-53078.firebasestorage.app',
    androidClientId: '468632398862-6q682eht3lil3f91h2a5tertlfpctmff.apps.googleusercontent.com',
    iosBundleId: 'com.chessever.desktop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUQe1l9HI_5C51FEc6FmUD_ps4hv0gWc4',
    appId: '1:468632398862:web:08a813ddf31e74ec2f605f',
    messagingSenderId: '468632398862',
    projectId: 'chessever-53078',
    authDomain: 'chessever-53078.firebaseapp.com',
    storageBucket: 'chessever-53078.firebasestorage.app',
    measurementId: 'G-90H74PKQGD',
  );
}
